In [25]:
#binary classification not more then 2 class 0-1 only form
#linearly seprable data
#independent variable should be continues/discrate value
#dependent variable only discreate (int)
#regression get fit the best fitline and predict
#logistic regression give a clasification two class only


In [26]:
#import package 
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt #used  mathematical computaion
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
churn=pd.read_csv("ChurnData.csv")
churn.head(4)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  

[4 rows x 28 columns]

In [28]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tenure    200 non-null    float64
 1   age       200 non-null    float64
 2   address   200 non-null    float64
 3   income    200 non-null    float64
 4   ed        200 non-null    float64
 5   employ    200 non-null    float64
 6   equip     200 non-null    float64
 7   callcard  200 non-null    float64
 8   wireless  200 non-null    float64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    float64
 18  pager     200 non-null    float64
 19  internet  200 non-null    float64
 20  callwait  200 non-null    float6

In [29]:
churn.tail(4)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[4 rows x 28 columns]

In [30]:
churn_df=churn[['tenure','age','address','ed','employ','equip','ebill','loglong','lninc','custcat','churn']]
churn_df.head(5)

tenure   age  address   ed  employ  equip  ebill  loglong  lninc  custcat  \
0    11.0  33.0      7.0  5.0     5.0    0.0    0.0    1.482  4.913      4.0   
1    33.0  33.0     12.0  2.0     0.0    0.0    0.0    2.246  3.497      1.0   
2    23.0  30.0      9.0  1.0     2.0    0.0    0.0    1.841  3.401      3.0   
3    38.0  35.0      5.0  2.0    10.0    1.0    1.0    1.800  4.331      4.0   
4     7.0  35.0     14.0  2.0    15.0    0.0    0.0    1.960  4.382      3.0   

   churn  
0    1.0  
1    1.0  
2    0.0  
3    0.0  
4    0.0

In [31]:
x=np.asarray(churn_df[['tenure','age','address','ed','employ','equip','ebill','loglong','lninc','custcat']])
x[0:5]

array([[11.   , 33.   ,  7.   ,  5.   ,  5.   ,  0.   ,  0.   ,  1.482,
         4.913,  4.   ],
       [33.   , 33.   , 12.   ,  2.   ,  0.   ,  0.   ,  0.   ,  2.246,
         3.497,  1.   ],
       [23.   , 30.   ,  9.   ,  1.   ,  2.   ,  0.   ,  0.   ,  1.841,
         3.401,  3.   ],
       [38.   , 35.   ,  5.   ,  2.   , 10.   ,  1.   ,  1.   ,  1.8  ,
         4.331,  4.   ],
       [ 7.   , 35.   , 14.   ,  2.   , 15.   ,  0.   ,  0.   ,  1.96 ,
         4.382,  3.   ]])

In [32]:
#churn_df['churn']=churn_df['churn'].astype('int')
y=np.asarray(churn_df[['churn']])
y[0:5]

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [33]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   tenure   200 non-null    float64
 1   age      200 non-null    float64
 2   address  200 non-null    float64
 3   ed       200 non-null    float64
 4   employ   200 non-null    float64
 5   equip    200 non-null    float64
 6   ebill    200 non-null    float64
 7   loglong  200 non-null    float64
 8   lninc    200 non-null    float64
 9   custcat  200 non-null    float64
 10  churn    200 non-null    float64
dtypes: float64(11)
memory usage: 17.3 KB


In [34]:
from sklearn import preprocessing
x=preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  1.6961288 , -0.58477841,
        -0.85972695, -0.88640526, -0.97509593,  1.28150384,  1.41630855],
       [-0.11604313, -0.62595491,  0.03454064, -0.6433592 , -1.14437497,
        -0.85972695, -0.88640526,  0.07226665, -0.60481397, -1.36987221],
       [-0.57928917, -0.85594447, -0.261522  , -1.42318853, -0.92053635,
        -0.85972695, -0.88640526, -0.48294519, -0.73269992,  0.48758163],
       [ 0.11557989, -0.47262854, -0.65627219, -0.6433592 , -0.02518185,
         1.16316   ,  1.12815215, -0.53915182,  0.50619525,  1.41630855],
       [-1.32048283, -0.47262854,  0.23191574, -0.6433592 ,  0.53441472,
        -0.85972695, -0.88640526, -0.31980887,  0.57413466,  0.48758163]])

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)


In [36]:
print("train_set",x_train.shape,y_train.shape)
print("test_set",x_test.shape,y_test.shape)

train_set (160, 10) (160, 1)
test_set (40, 10) (40, 1)


In [37]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(C=0.01,solver='liblinear').fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
yhat=LR.predict(x_test)#predict value/model

In [40]:
yhat

array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1.])

In [41]:
#probability
yhat_proba=LR.predict_proba(x_test)
yhat_proba

array([[0.54755355, 0.45244645],
       [0.6259893 , 0.3740107 ],
       [0.61530961, 0.38469039],
       [0.62139259, 0.37860741],
       [0.60809203, 0.39190797],
       [0.56210272, 0.43789728],
       [0.4961854 , 0.5038146 ],
       [0.64555399, 0.35444601],
       [0.3830984 , 0.6169016 ],
       [0.59292819, 0.40707181],
       [0.53917047, 0.46082953],
       [0.61754524, 0.38245476],
       [0.44769926, 0.55230074],
       [0.4006498 , 0.5993502 ],
       [0.64707299, 0.35292701],
       [0.57744294, 0.42255706],
       [0.53835463, 0.46164537],
       [0.53871338, 0.46128662],
       [0.46175375, 0.53824625],
       [0.52519014, 0.47480986],
       [0.61915719, 0.38084281],
       [0.49416159, 0.50583841],
       [0.70702619, 0.29297381],
       [0.4660325 , 0.5339675 ],
       [0.48059273, 0.51940727],
       [0.72076061, 0.27923939],
       [0.48634317, 0.51365683],
       [0.47111469, 0.52888531],
       [0.55342966, 0.44657034],
       [0.76565809, 0.23434191],
       [0.

In [42]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test,yhat)

C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.6

In [43]:
from sklearn.metrics import classification_report
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

         0.0       0.67      0.72      0.69        25
         1.0       0.46      0.40      0.43        15

    accuracy                           0.60        40
   macro avg       0.56      0.56      0.56        40
weighted avg       0.59      0.60      0.59        40



In [44]:
#precision and recall important to give best f1_score